"""empty message

Revision ID: 6d575b034fb6
Revises: 
Create Date: 2021-03-23 21:55:24.659603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d575b034fb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('dscription', sa.String(length=500), nullable=True),
    sa.Column('no_rooms', sa.String(length=15), nullable=True),
    sa.Column('no_bathrooms', sa.String(length=15), nullable=True),
    sa.Column('price', sa.String(length=150), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.Column('photo', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
